name: Release on tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --noconsole --clean --icon=liver.ico Office-Escape.py

      - name: Zip the artifact
        run: |
          cd dist
          powershell Compress-Archive -Path Office-Escape.exe -DestinationPath Office-Escape.zip

      - name: Generate SHA256 checksum
        run: |
          cd dist
          powershell -command "Get-FileHash Office-Escape.exe -Algorithm SHA256 | Format-List" > checksum.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-files
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-files
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/Office-Escape.exe
            dist/Office-Escape.zip
            dist/checksum.txt
